theme: jekyll-theme-slate
title: Optimization Of Neural Style Transfer On Native Mobile
description: "Final Project for BBM480 Design Project Course @Hacettepe University <br/> <strong>Supervisor:</strong> Assoc. Prof. NAZLI İKİZLER CİNBİŞ"